modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
logoFile="forcedseed_logo.png"

[[mods]]
modId="forcedseed"
version="1.0.0"
displayName="Forced Seed"
description="Automatically forces a fixed seed for all new worlds"
authors="JonasPfi"

[[dependencies.forcedseed]]
modId="forge"
mandatory=true
versionRange="[47.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.forcedseed]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"